; Listing generated by Microsoft (R) Optimizing Compiler Version 19.00.24210.0 

	TITLE	D:\Maxim\projects\GitHub\LifeEngine\lifeEngine\lifeEngine\Utils\OpenGL\glm\glm\detail\dummy.cpp
	.686P
	.XMM
	include listing.inc
	.model	flat

INCLUDELIB MSVCRT

PUBLIC	_main
; Function compile flags: /Ogtp
; File d:\maxim\projects\github\lifeengine\lifeengine\lifeengine\utils\opengl\glm\glm\detail\dummy.cpp
;	COMDAT _main
_TEXT	SEGMENT
_main	PROC						; COMDAT

; 191  : /*
; 192  : 	glm::vec1 o(1);
; 193  : 	glm::vec2 a(1);
; 194  : 	glm::vec3 b(1);
; 195  : 	glm::vec4 c(1);
; 196  : 
; 197  : 	glm::quat q;
; 198  : 	glm::dualquat p;
; 199  : 
; 200  : 	glm::mat4 m(1);
; 201  : 
; 202  : 	float a0 = normalizeDotA(a, a);
; 203  : 	float b0 = normalizeDotB(b, b);
; 204  : 	float c0 = normalizeDotC(c, c);
; 205  : */
; 206  : 	return 0;

	xor	eax, eax

; 207  : }

	ret	0
_main	ENDP
_TEXT	ENDS
END
